# Generated by Django 6.0.1 on 2026-01-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Όνομα Παιδιού')),
                ('last_name', models.CharField(max_length=50, verbose_name='Επώνυμο Παιδιού')),
                ('date_of_birth', models.DateField(verbose_name='Ημερομηνία Γέννησης')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Ονοματεπώνυμο Γονέα')),
                ('parent_phone', models.CharField(max_length=15, verbose_name='Τηλέφωνο')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Διεύθυνση')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ασθενής',
                'verbose_name_plural': 'Ασθενείς',
            },
        ),
    ]
