# Generated by Django 6.0.1 on 2026-01-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('time', models.TimeField(verbose_name='Ώρα')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Προγραμματισμένο'), ('COMPLETED', 'Ολοκληρώθηκε'), ('CANCELLED', 'Ακυρώθηκε'), ('NO_SHOW', 'Δεν εμφανίστηκε')], default='SCHEDULED', max_length=20, verbose_name='Κατάσταση')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις Θεραπείας')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='office.patient', verbose_name='Ασθενής')),
            ],
            options={
                'verbose_name': 'Ραντεβού',
                'verbose_name_plural': 'Ραντεβού',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
