# Generated by Django 6.0.1 on 2026-01-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='Έχει Τιμολογηθεί;'),
        ),
    ]
