# Generated by Django 6.0.1 on 2026-01-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_appointment_is_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='next_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Επόμενη Τιμολόγηση'),
        ),
    ]
